# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='FirstAppUser',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
